### ISSUE TITLE
Congrats on the open source, but where is code and issues?

### ISSUE THREAD

**Issue by JunpingDu** [polaris-catalog/polaris#1]
Hope to see the code ASAP.

**Comment by skashmeri** [comment]
`Polaris Catalog will be open sourced under an Apache 2.0 license in the **next 90 days**. In the meantime:`

**Comment by skashmeri** [comment]
> Hope to see the code ASAP.

`Polaris Catalog will be open sourced under an Apache 2.0 license in the **next 90 days**. In the meantime:`
