### ISSUE TITLE
[BUG] Polaris will not build with Dockerfile on Windows 11

### ISSUE THREAD

**Issue by zielyn** [polaris-catalog/polaris#126]
### Is this a possible security vulnerability?

- [X] This is NOT a possible security vulnerability

### Describe the bug

I'm on windows 11 with Docker Desktop v4.33.1

Running the command `docker build -t localhost:5001/polaris:latest .` results in an error after the change to the image was done in commit https://github.com/polaris-catalog/polaris/commit/0f2c2a8acde387a8a107d30631a6496cc43abb13

If i revert the Dockerfile to the code before this commit, I can build the image. I've been able to reproduce this error along with a colleague where we are all on windows 11 using docker desktop to build the image.

### To Reproduce

1. Have Windows 11 as your base OS.
2. Have Docker Desktop installed. 
3. Open Terminal and traverse to the git repo location with the latest commit.
4. Run the command `docker build -t localhost:5001/polaris:latest .`

### Actual Behavior

Error Message:

```
 => ERROR [build 5/5] RUN ./gradlew --no-daemon --info clean shadowJar                                                                                               0.5s
------
 > [build 5/5] RUN ./gradlew --no-daemon --info clean shadowJar:
0.416 /bin/sh: ./gradlew: /bin/sh^M: bad interpreter: No such file or directory
------

 1 warning found (use docker --debug to expand):
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 19)
Dockerfile:29
```

### Expected Behavior

The docker image should build without error.

### System information

OS Name:                   Microsoft Windows 11 
OS Version:                10.0.22631 N/A Build 22631

Docker Desktop Personal v4.33.1 with wsl 2 based engine enabled.

**Comment by MonkeyCanCode** [comment]
@zielyn This is actually not a bug of the program but rather how diff OS handing line endings. Here is what you can do to be able to build on Windows:
1. Delete the repo you just cloned
2. Run `git config --global core.autocrlf input`
3. Clone down repo again ` git clone https://github.com/polaris-catalog/polaris.git`
4. Build it ` docker build -t localhost:5001/polaris -f Dockerfile .`

Here is the reasoning: Windows use carriage return and line feed (CRLF) while Unix/Linux use line feed (LF) for line endings. With the git config listed on item 2, it will automatically convert `CRLF` to `LF` before pushing the files into docker. By doing so, the container will then read the file as its and the file will be using LF for for line endings which won't raise the issue listed above.
