### ISSUE TITLE
[FEATURE REQUEST] Use Github Action to check Markdown links

### ISSUE THREAD

**Issue by kevinjqliu** [polaris-catalog/polaris#139]
### Is your feature request related to a problem? Please describe.

Use [github-action-markdown-link-check](https://github.com/gaurav-nelson/github-action-markdown-link-check) Github Action to check for dead links in Markdown files. 

Similar to [iceberg-python#324](https://github.com/apache/iceberg-python/pull/324)

**Comment by apd-bbrewington** [comment]
Easy enough!  I'm working on this one if you want to add me as Assignee

**Comment by bbrewington** [comment]
I'm working on this on a fork, and will PR in

Just read CONTRIBUTING.md, and emailing over my ICLA now

**Comment by kevinjqliu** [comment]
I had a PR started, but feel free to work on this! Feel free to add me as a reviewer

Should cover both `docs/` and `regtests/client/python/docs`
![Screenshot 2024-08-11 at 10 45 34 AM](https://github.com/user-attachments/assets/f254e085-bb03-45cc-8138-1d625a1311d0)

**Comment by kevinjqliu** [comment]
As a follow up, enable this github action for all MD files and for all PRs
See comment: https://github.com/apache/polaris/pull/141#discussion_r1726148135
