### ISSUE TITLE
[FEATURE REQUEST] Add #polaris channel in Iceberg Slack

### ISSUE THREAD

**Issue by kevinjqliu** [polaris-catalog/polaris#140]
### Is your feature request related to a problem? Please describe.

A way to discuss Polaris in the Iceberg slack. 
See https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1723227474343279

**Comment by flyrain** [comment]
I don't have the permission to create new channel. I remember I was able to do so :-(.

**Comment by kevinjqliu** [comment]
I think we need to ask a slack workspace admin to add a channel

**Comment by kevinjqliu** [comment]
Added! (thanks ryan)
https://apache-iceberg.slack.com/archives/C07HADW86HZ
