### ISSUE TITLE
[DOC] Quickstart guide link leads to non-existent file

### ISSUE THREAD

**Issue by kferenc3** [polaris-catalog/polaris#31]
The Bootstrapping Polaris section has the following sentence with a link:
"For more information on how to configure Polaris for production usage, see the [docs]." The link leads to the following page, but it doesn't exist: https://github.com/polaris-catalog/polaris/blob/main/docs/configuring-polaris-for-production.md

**Comment by eric-maynard** [comment]
Thanks @kferenc3 -- I'm hoping to resolve this with https://github.com/polaris-catalog/polaris/pull/43/commits

**Comment by annafil** [comment]
Fixed by https://github.com/polaris-catalog/polaris/pull/43/! Thanks @eric-maynard for getting the fix in and @kferenc3 for reporting this 🙏
