### ISSUE TITLE
[BUG] Integration Test fails (PolarisSparkIntegrationTest)

### ISSUE THREAD

**Issue by mths1** [polaris-catalog/polaris#38]
**Describe the bug**

./gradlew build

results in a test failure 

![image](https://github.com/user-attachments/assets/ac8e616f-90c7-4a4c-ad54-99908cd0fec0)

RHEL 9
java --version
```
openjdk 21.0.4 2024-07-16 LTS
OpenJDK Runtime Environment (Red_Hat-21.0.4.0.7-1) (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-21.0.4.0.7-1) (build 21.0.4+7-LTS, mixed mode, sharing)
```

javac --version
```
javac 21.0.4
```

**Is this a possible security vulnerability?** 
- [ ] yes -- if yes, stop here and contact security@polaris.io instead
- [x] no 

**To Reproduce**
./gradlew build
See error

**Expected behavior**
Builds without test failures

**Screenshots**

**System info (please complete the following information):**
 - OS:  RHEL 9
 - Polaris Catalog Version [e.g. 0.3.0] main branch

**Additional context**

**Comment by RussellSpitzer** [comment]
Is Docker running on your machine? The Spark integration tests require Docker.

**Comment by mths1** [comment]
Thanks for your support. There is "docker", as in docker -v

docker -v
```
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
podman version 4.9.4-rhel
```

(btw: in the readme, docker is only mentioned "If you want to run the project in a containerized environment.", not for ./gradlew build)

**Comment by RussellSpitzer** [comment]
I'm using Docker for Desktop in OSX, I'm not sure what the RHEL equivalent would be. We should probably add details of that to the documentation. When I wasn't running docker, the Spark suite failed.

**Comment by AlexMercedCoder** [comment]
I also had the tests fail when I used the built in docker-compose.yml here is my docker version:
```
Docker version 20.10.14, build a224086
```
I'm working off an ubuntu based OS

**Comment by flyrain** [comment]
Hit the same issue in MacOS. It has gone once I start the docker.

I am using `Docker version 27.0.3`, which is a pretty new one, the latest version is 27.1.  So I assume it fails on certain old versions. I can add a docker version suggestion in the readme.
