### ISSUE TITLE
[FEATURE REQUEST] Support for S3 compatible services

### ISSUE THREAD

**Issue by guitcastro** [polaris-catalog/polaris#60]
**Is your feature request related to a problem? Please describe.**
Support for S3 compatible services like min.io, cloudflare r2 and etc. 

**Describe the solution you'd like**
Allow other services compatible with S3 instead of just AWS. 

**Describe alternatives you've considered**
Only options are use one of the supported storage.

**Additional context**

You might want to try do add a generic implementation to handle all S3 compatibles generic services, but will not be possible to have specific credentials per principal. 

Or try to keep different implementations, per example use cloudflare R2 api token to generate new access_key and secrets for each principal with a limited scoped.   

I am using cloudflare, thus I have interest in implement this feature. Just wanna know if do you have plans to create a generic S3 support or I should focus on a specific implementation (R2) to allow principal credentials revocation.

**Comment by snazy** [comment]
Isn't this a duplicate of #32?

**Comment by guitcastro** [comment]
@snazy Yes it is. Sorry about that.
