### ISSUE TITLE
[DOC] Directions to run mini-deployment reference k8 directory that does not exist

### ISSUE THREAD

**Issue by bzillins** [polaris-catalog/polaris#99]
**Describe the bug**
The first step of "Running in Kubernetes" instruct you to execute setup.sh
setup.sh tries to apply [k8/deployment.yaml](kubectl delete -f k8/deployment.yaml --ignore-not-found) and that dir does not exist

**Is this a possible security vulnerability?** 
no

**To Reproduce**
Attempt to navigate to the k8 dir in the repo

**Additional context**
Thank you for all the work that has gone into releasing this so far! Based on the commit from Dennis Huo that references another polaris-k8-config repo my assumption is that a few files were missed.

The docker compose file has enough context to put together a replacement for now.

A search for "k8" and "k8s" didn't show any related issues.

**Comment by flyrain** [comment]
That's right. The file `deployment.yaml` is missing.

**Comment by MonkeyCanCode** [comment]
If the file doesn't exist, I can take it over and create a PR for it.

**Comment by MonkeyCanCode** [comment]
Sample PR up in https://github.com/polaris-catalog/polaris/pull/102
